## **Welcome to Pytorch tutorial for basic Tensor Operations---------------**

Pytorch mainly deals with "**Tensors**" and its associated operations. The best part is you can use both **CPU** as well as **GPU** for all ur Tensors and model optimisations. Pytorch gives you enormous flexibility and powerful GPU support for all it operations.  
<br>
**Note** : Check the documentation (https://pytorch.org/) for the CUDA compatibility of your **GPU** before getting started.
<br><br>
Lets get started ----------------------------------------------------------------------------

# **1.** Installing Pytorch ver 0.4.1

In [1]:
!pip install torch

    100% |████████████████████████████████| 519.5MB 28kB/s 
tcmalloc: large alloc 1073750016 bytes == 0x59cf6000 @  0x7f8b6e6c91c4 0x46d6a4 0x5fcbcc 0x4c494d 0x54f3c4 0x553aaf 0x54e4c8 0x54f4f6 0x553aaf 0x54efc1 0x54f24d 0x553aaf 0x54efc1 0x54f24d 0x553aaf 0x54efc1 0x54f24d 0x551ee0 0x54e4c8 0x54f4f6 0x553aaf 0x54efc1 0x54f24d 0x551ee0 0x54efc1 0x54f24d 0x551ee0 0x54e4c8 0x54f4f6 0x553aaf 0x54e4c8


# **2.** Import **torch**. 
<br>
All the Tensor operations will be done using **torch.Tensor** module. 
<br>
Pytorch gives you power to dynamically switch between traditional numpy ndarrays and torch based Tensors. 
<br>
<br>
** -- ** A 1-d Tensor is a vector 
<br>
** -- ** A 2-d Tensor is a matrix 
<br>
** -- ** A 3-d Tensor is a **vector** of identical matrices 
<br>
** -- ** A 4-d Tensor is a **matrix** of identical matrices 
<br>

In [0]:
import torch as t

# **3.** Creating your first **tensor**.

In [3]:
x = t.Tensor(5)
x.size()

torch.Size([5])

In [4]:
y = t.Tensor(4,5)
y.size()

torch.Size([4, 5])

**Note** : **Tensor.fill_()** is in-place function for fill() command.

In [5]:
x.fill_(5)

tensor([5., 5., 5., 5., 5.])

In [6]:
y.fill_(7)

tensor([[7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7.]])

# **4.** Basic Tensor arithmetics

In [8]:
x.sum()


tensor(25.)

In [9]:
y.mean()

tensor(7.)

In [10]:
y.std()

tensor(0.)

# **5.** Turning numpy arrays to Pytorch Tensors.

In [0]:
import numpy as np

In [16]:
a = np.zeros((4,5))  #the type is array
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
a1 = t.from_numpy(a)   #the type is tensor
a1

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

# **6.** Viewing, Slicing, Expanding your **Tensors**

In [20]:
x = t.Tensor([ [ 1, 3, 0 ],[ 2, 4, 6 ] ])
x

tensor([[1., 3., 0.],
        [2., 4., 6.]])

**Note** : By default , **torch.Tensor** is an alias for **torch.FloatTensor**. You can change it using **torch.set_default_tensor_type**

In [21]:
x.t()   #Transpose

tensor([[1., 2.],
        [3., 4.],
        [0., 6.]])

In [22]:
x.view(1,-1)           #View lets you get the Tensor of desired shape from a given Tensor.

tensor([[1., 3., 0., 2., 4., 6.]])

**Note** Use (-1) as the index when you are uncertain about the number of row/columns which would appear after viewing. 
<br> 
In the above example , I wanted to  view my Tensor as only a single row but didnt know how many columns that would require to adjust the values. 
<br>
(**Thats not true :P**)

In [23]:
x.view(-1) #Equivalent

tensor([1., 3., 0., 2., 4., 6.])

In [25]:
x.view(3,-1)   #Note how it is different from x.t()

tensor([[1., 3.],
        [0., 2.],
        [4., 6.]])

**Tensor.narrow(dim, start, length)** : Another useful operation for creating new Tensors which is a sub-part of an existing Tensor, by constraining along one of the dimensions which can be row/column/channel et-al depending on your **Tensor.size()**. 
<br>

** ---** It shares its contents with the original **Tensor** and modifying one changes the other.

In [27]:
a = t.Tensor(4,5).normal_()
a

tensor([[-0.9450, -0.8588, -0.7289,  1.0843, -0.4016],
        [ 1.4458, -0.4735, -0.5568,  0.7486, -0.6572],
        [-0.3240, -0.5077,  1.5484,  0.5645, -0.4366],
        [ 1.0366, -0.1732, -0.3483, -1.7900,  0.2823]])

In [28]:
a.narrow(1,0,3)    

tensor([[-0.9450, -0.8588, -0.7289],
        [ 1.4458, -0.4735, -0.5568],
        [-0.3240, -0.5077,  1.5484],
        [ 1.0366, -0.1732, -0.3483]])

** --- ** "a" is a Two dimensional tensor, so param **dim** can be either **0 : row or 1 : column**
<br>
** --- ** For a 3-D Tensor, **dim** can be **0 : channels or 1 : row or 2 : column**

In [30]:
a.narrow(0,2,2).fill_(1)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [31]:
a   #Modifying one changes the other. Beware!!

tensor([[-0.9450, -0.8588, -0.7289,  1.0843, -0.4016],
        [ 1.4458, -0.4735, -0.5568,  0.7486, -0.6572],
        [ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000],
        [ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000]])

** ---** To **expand** your tensor channels, first add a channel dimension to your Tensor (if absent) in the **torch.view()** and then use **Tensor.expand()** to expand your channels.

In [32]:
a.view(1,5,-1).expand(3,5,-1) #one channel expanded to 3 channels

tensor([[[-0.9450, -0.8588, -0.7289,  1.0843],
         [-0.4016,  1.4458, -0.4735, -0.5568],
         [ 0.7486, -0.6572,  1.0000,  1.0000],
         [ 1.0000,  1.0000,  1.0000,  1.0000],
         [ 1.0000,  1.0000,  1.0000,  1.0000]],

        [[-0.9450, -0.8588, -0.7289,  1.0843],
         [-0.4016,  1.4458, -0.4735, -0.5568],
         [ 0.7486, -0.6572,  1.0000,  1.0000],
         [ 1.0000,  1.0000,  1.0000,  1.0000],
         [ 1.0000,  1.0000,  1.0000,  1.0000]],

        [[-0.9450, -0.8588, -0.7289,  1.0843],
         [-0.4016,  1.4458, -0.4735, -0.5568],
         [ 0.7486, -0.6572,  1.0000,  1.0000],
         [ 1.0000,  1.0000,  1.0000,  1.0000],
         [ 1.0000,  1.0000,  1.0000,  1.0000]]])

In [33]:
a.view(1,5,-1).expand(2,5,-1)   #one channel expanded to 2 channels
                                # Go on.. play around to discover more

tensor([[[-0.9450, -0.8588, -0.7289,  1.0843],
         [-0.4016,  1.4458, -0.4735, -0.5568],
         [ 0.7486, -0.6572,  1.0000,  1.0000],
         [ 1.0000,  1.0000,  1.0000,  1.0000],
         [ 1.0000,  1.0000,  1.0000,  1.0000]],

        [[-0.9450, -0.8588, -0.7289,  1.0843],
         [-0.4016,  1.4458, -0.4735, -0.5568],
         [ 0.7486, -0.6572,  1.0000,  1.0000],
         [ 1.0000,  1.0000,  1.0000,  1.0000],
         [ 1.0000,  1.0000,  1.0000,  1.0000]]])

In [36]:
b = t.Tensor([ [ [ 1, 2, 1 ],[ 2, 1, 2 ] ],[ [ 3, 0, 3 ],[ 0, 3, 0 ] ] ])   # b has two channels
b

tensor([[[1., 2., 1.],
         [2., 1., 2.]],

        [[3., 0., 3.],
         [0., 3., 0.]]])

In [37]:
b.narrow(0,1,1)    #1st parameter is 0 : channel

tensor([[[3., 0., 3.],
         [0., 3., 0.]]])

In [38]:
b.narrow(1,0,2)    #1st parameter is 1 : row

tensor([[[1., 2., 1.],
         [2., 1., 2.]],

        [[3., 0., 3.],
         [0., 3., 0.]]])

In [39]:
b.narrow(2,0,2)

tensor([[[1., 2.],
         [2., 1.]],

        [[3., 0.],
         [0., 3.]]])

# **7.** Broadcasting Tensors <br>
** --- ** Expands dimensions by size 1 by replicating coefficients, when necessary for certain operations.

In [0]:
a = t.Tensor([[1] , [2] , [3] , [4]])
b = t.Tensor([[5 , -5, 5, -5, 5]])


In [44]:
a

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [45]:
b

tensor([[ 5., -5.,  5., -5.,  5.]])

In [46]:
a+b

tensor([[ 6., -4.,  6., -4.,  6.],
        [ 7., -3.,  7., -3.,  7.],
        [ 8., -2.,  8., -2.,  8.],
        [ 9., -1.,  9., -1.,  9.]])

# **8.** Torch "Storage" : Going Deeper 
<br>
** --- ** A Tensor is basically a view of low level **storage()**

In [48]:
a = t.Tensor(4,6).zero_()
a

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [49]:
a_store = a.storage()    #4*6 stored  as 24*1
a_store  

 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
[torch.FloatStorage of size 24]

In [51]:
a_store[5] = 65    #Modifying values at low level changes it at high level as well.
a

tensor([[ 0.,  0.,  0.,  0.,  0., 65.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.]])

** Note ** : **Tensor.narrow()** ,**Tensor.view()** ,**Tensor.expand()** and various others share the same storage as the original Tensor as was seen previously. 

# **9.** Creating Tensors on **GPU** using **cuda()**
<br>
** ---** Untill now , all tensors created were by default stored on CPU.
<br>
** --- ** To harness the power of GPU computation, create Tensors using **cuda()**

In [56]:
a = t.Tensor(5,6).normal_()
a

tensor([[-0.0859, -0.8396,  0.4854, -0.0655,  0.4835,  1.0850],
        [-1.1504,  0.5270, -2.5013,  1.0748,  0.8188, -0.5173],
        [ 1.0104,  1.8889, -1.1886,  0.2656,  0.0810,  1.2346],
        [ 0.9876,  0.2566,  2.3871, -0.9473, -1.2344,  0.7946],
        [ 0.7185,  0.0789, -0.4640, -0.3758,  0.1731,  0.1237]])

In [60]:
a = a.cuda()
a

tensor([[-0.0859, -0.8396,  0.4854, -0.0655,  0.4835,  1.0850],
        [-1.1504,  0.5270, -2.5013,  1.0748,  0.8188, -0.5173],
        [ 1.0104,  1.8889, -1.1886,  0.2656,  0.0810,  1.2346],
        [ 0.9876,  0.2566,  2.3871, -0.9473, -1.2344,  0.7946],
        [ 0.7185,  0.0789, -0.4640, -0.3758,  0.1731,  0.1237]],
       device='cuda:0')

The Tensor is created on stored on cuda device with **id : 0**

In [61]:
t.cuda.get_device_name(0)    # This proves our Tensors were indeed stored on a GPU . NVIDIA Tesla K80

'Tesla K80'

## ** --------------------------------------------- THE END!! ---------------------------------------------** 